# values.yaml
role: "Aggregator"

replicas: 5

customConfig:
  api:
      enabled: true
      address: 127.0.0.1:8686
  sources:
    demo_logs:
      type: demo_logs
      interval: 0.001
      format: json

  transforms:
    parse_message:
      type: remap
      inputs: ["demo_logs"]
      source: |
        . = parse_json!(.message)
        del(.message) 

  sinks:
    loki:
      type: loki
      inputs:
        - parse_message
      endpoint: "http://loki-gateway.loki.svc.cluster.local:80"
      encoding:
        codec: json
      labels:
        job:    "vector"
        host:   "${HOSTNAME}"
        method: "{{`{{ method }}`}}"
        status: "{{`{{ status }}`}}"
        user:   "{{`{{ user-identifier }}`}}"